GET http://localhost:8000/movies

###

GET http://localhost:8000/movies/123456

###

POST http://localhost:8000/api/v1/movies
Content-Type: application/json

{
    "title":"Kung Fu Panda",
    "genre":"Animation",
    "released":"2008"
}

###

PATCH http://localhost:8000/movies/123456
Content-Type: application/json

{
    "title":"Kung Fu Panda",
    "genre":"Animation",
    "released":"2007"
}
###

DELETE http://localhost:8000/movies/123456